<a href="https://colab.research.google.com/github/tigureis/Notes_and_exercises_on_Data_Structuring/blob/main/merge_concat_join.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Libraries

In [1]:
import numpy as np
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt

import plotly.express as px

from sklearn import datasets

from IPython.core.display import HTML
from ipywidgets import interact, widgets

This code snippet utilizes the *Seaborn library* (`sns`) to customize the appearance of the plots in this project.

In [2]:
sns.set_theme(
    context='talk',
    style='ticks',
    font_scale=.8,
    rc={
        'figure.figsize': (12,8)
    }
)

Implement a function *`display_side_by_side`* to display multiple Pandas DataFrames side-by-side.

In [3]:
def display_side_by_side(dataframes:list,titles:list):
    html_str=''
    for df,title in zip(dataframes, titles):
        html_str+=f'<span>{title}:</span>'
        html_str+=df.to_html().replace('table','table style="display:inline"')
        html_str+="&nbsp"*10
    display(HTML(html_str))

# [merge](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html)

 creates two *Pandas* DataFrames

In [5]:
df1 = pd.DataFrame(
    {
        "key": ["K0", "K1", "K2", "K3"],
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
    }, index=range(4)
)

df2 = pd.DataFrame(
    {
        "key": ["K1", "K2", "K3", "K4"],
        "C": ["C1", "C2", "C3", "C4"],
        "D": ["D1", "D2", "D3", "D4"],
    }, index=range(1,5)
)

Display both DFs

In [6]:
display_side_by_side([df1,df2],['df1','df2'])

Joint both DFs using `merge`

In [7]:
df1.merge(df2, how='inner', on='key')

  key   A   B   C   D
0  K1  A1  B1  C1  D1
1  K2  A2  B2  C2  D2
2  K3  A3  B3  C3  D3

Comparing the results of `inner join`, `left join`, and `right join`

In [8]:
df_inner = df1.merge(df2, how='inner', on='key')
df_left = df1.merge(df2, how='left', on='key')
df_right = df1.merge(df2, how='right', on='key')

display_side_by_side(
    [df1, df2, df_inner,df_left,df_right],
    ['df1','df2','inner_join','left_join','right_join']
)

Define an interactive function to demonstrate different types of joins between two Pandas DataFrames.

In [9]:
@interact(method=['inner','left','right','outer'])
def merge (method):
  df_merge=df1.merge(df2, how=method)
  display_side_by_side(
      [df1, df2, df_merge],
      ['df1','df2',f'{method}_join']
  )

interactive(children=(Dropdown(description='method', options=('inner', 'left', 'right', 'outer'), value='inner…

# [Concat](https://pandas.pydata.org/docs/reference/api/pandas.concat.html)

In [10]:
df_A = df1.iloc[:2]
df_B = df1.iloc[2:]
display_side_by_side([df_A,df_B], ['df_A','df_B'])

Difference between horizontal and vertical concaternation

In [11]:
concat_vert = pd.concat([df_A,df_B])
concat_horiz = pd.concat([df_A,df_B], axis=1)
concat_horiz_FSI = pd.concat([df_A,df_B.reset_index()], axis=1)
display_side_by_side([
    concat_vert,
    concat_horiz,
    concat_horiz_FSI
    ],[
    'concat_vert',
    'concat_horiz',
    'concat_horiz_FSI'])

# [join](https://)

In [13]:
df_left = pd.DataFrame({
    'A':['A0', 'A1', 'A2'],
    'B':['B0','B1','B2']
}, index=['K0','K1','K2'])

df_right = pd.DataFrame({
    'C':['C0','C1', 'C2'],
    'D':['D0','D1','D2']
}, index=['K0','K2','K3'])

df_join = df_left.join(df_right, how='inner')

`join` combine DataFrames based on their indexes. It's similar to `merge` but focuses on using the index as the join key rather than specifying columns.

In [14]:
display_side_by_side([df_left, df_right, df_join],['df_left', 'df_right', 'df_join'] )